version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start

  # Production service
  prod:
    build: .
    ports:
      - "1337:80"
    environment:
      - NODE_ENV=production 