version: '2.2'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - star-chart-data:/app/data
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    restart: unless-stopped

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - star-chart-data:/app/data
    ports:
      - "1337:3000"
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  star-chart-data: 