version: '2.2'

services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:80"
    environment:
      - NODE_ENV=production 